spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oj_online?characterEncoding=utf8&useSSL=false
    username: root
    password: g641517196
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:./mapper/**Mapper.xml